export const UserActionsTypes = {
  //register actionsTypes
  REGISTER_REQUEST_OR_LOGIN: 'REGISTER_REQUEST_OR_LOGIN',

  //login actionsTypes
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT: 'USERS_LOGOUT',
  SET_TWO_FACTOR_TOKEN: 'SET_TWO_FACTOR_TOKEN',

  //signUpProcess actionsTypes
  LOADING_DATA_SIGN_UP_PROCESS: 'LOADING_DATA_SIGN_UP_PROCESS',
  CHANGE_STEP: 'CHANGE_STEP',
  GET_MARKETPLACES: 'GET_MARKETPLACES',
  SELECT_MARKETPLACES: 'SELECT_MARKETPLACES',
  CHANGE_TOTAL_COST: 'CHANGE_TOTAL_COST',
  ON_SELECT_SCRAPING_SCHEDULE: 'ON_SELECT_SCRAPING_SCHEDULE',
  ON_SELECT_SCRAPING_TIME_OF_DAY: 'ON_SELECT_SCRAPING_TIME_OF_DAY',
  ON_SET_PERSONAL_INFORMATION: 'ON_SET_PERSONAL_INFORMATION',
  ON_SET_SCRAPING_SCHEDULE_FREQUENCY: 'ON_SET_SCRAPING_SCHEDULE_FREQUENCY',
  SELECT_ANNUAL_OR_MONTHLY: 'SELECT_ANNUAL_OR_MONTHLY',
  SET_PAYMENT_METHOD_ID: 'SET_PAYMENT_METHOD_ID',
  SET_PREMIUM_TIME_PRICE: 'SET_PREMIUM_TIME_PRICE',
  CHANGE_PAY_PRICE: 'CHANGE_PAY_PRICE',
  CHANGE_REFERRAL_CODE_DISCOUNT: 'CHANGE_REFERRAL_CODE_DISCOUNT',
  CHANGE_COUPON_CODE_DISCOUNT: 'CHANGE_COUPON_CODE_DISCOUNT',

  //products actionsTypes
  GET_MARKETPLACES_PRODUCTS: 'GET_MARKETPLACES_PRODUCTS',
  GET_PRODUCTS: 'GET_PRODUCTS',
  EDIT_PRODUCTS: 'EDIT_PRODUCTS',
  GET_REPORT_PRODUCTS: 'GET_REPORT_PRODUCTS',
  SET_ENTRY_MARKET: 'SET_ENTRY_MARKET',
  SET_ENTRY_PRODUCT: 'SET_ENTRY_PRODUCT',
  SET_ALL_PRODUCTS_EMPTY: 'SET_ALL_PRODUCTS_EMPTY',
  SET_ENTRY_CHANGED_PRODUCT: 'SET_ENTRY_CHANGED_PRODUCT',
  LOADING_MARKETPLACES_PRODUCTS: 'LOADING_MARKETPLACES_PRODUCTS',
  LOADING_PRODUCTS: 'LOADING_PRODUCTS',
  FIRST_LOGGED: 'FIRST_LOGGED',
  GET_ANALYTICS_DATA: 'GET_ANALYTICS_DATA',
  LOADING_ANALYTICS_DATA: 'LOADING_ANALYTICS_DATA',
  FIRST_ADD_PRODUCT: 'FIRST_ADD_PRODUCT',
  ALLOW_MARKETS: 'ALLOW_MARKETS',
  SET_ENTRY_SELLER: 'SET_ENTRY_SELLER',
  DELETE_ALL_PRODUCTS: 'DELETE_ALL_PRODUCTS',
  PRODUCT_CURRENT_PAGE: 'PRODUCT_CURRENT_PAGE',
  ALL_PRODUCT_COUNT: 'ALL_PRODUCT_COUNT',
  NEW_ENTRY_PRODUCTS: 'NEW_ENTRY_PRODUCTS',

  //admin retailers actionsTypes
  GET_ADMIN_RETAILERS: 'GET_ADMIN_RETAILERS',
  LOADING_ADMIN_RETAILERS_DATA: 'LOADING_ADMIN_RETAILERS_DATA',
  EDIT_ADMIN_RETAILERS_DATA: 'EDIT_ADMIN_RETAILERS_DATA',
  SET_FREQUENCY_MULTIPLE: 'SET_FREQUENCY_MULTIPLE',
  SET_RETAILER_LOCATION_PATHS: 'SET_RETAILER_LOCATION_PATHS',
  SET_EMPTY_RETAILER: 'SET_EMPTY_RETAILER',

  //admin sellers actionTypes
  LOADING_ADMIN_SELLERS_DATA: 'LOADING_ADMIN_SELLERS_DATA',
  GET_ADMIN_SELLERS: 'GET_ADMIN_SELLERS',
  UPDATE_ADMIN_SELLERS: 'UPDATE_ADMIN_SELLERS',

  //admin statistics actionTypes
  GET_ADMIN_STATISTICS: 'GET_ADMIN_STATISTICS',

  //admin customers actionTypes
  GET_ADMIN_CUSTOMERS: 'GET_ADMIN_CUSTOMERS',
  GET_ADMIN_CUSTOMER: 'GET_ADMIN_CUSTOMER',
  LOADING_ADMIN_CUSTOMERS_DATA: 'LOADING_ADMIN_CUSTOMERS_DATA',

  //admin support actionTypes
  GET_ADMIN_SUPPORTS: 'GET_ADMIN_SUPPORTS',
  GET_UNSEEN_SUPPORTS_COUNT: 'GET_UNSEEN_SUPPORTS_COUNT',
  GET_NEW_SUPPORT_NOTIFICATION: 'GET_NEW_SUPPORT_NOTIFICATION',

  //account settings change fields actionTypes
  ACCOUNT_SETTINGS_CHANGE_FIELD: 'ACCOUNT_SETTINGS_CHANGE_FIELD',

  //scrapping settings actionTypes
  GET_SELECTED_MARKETS: 'GET_SELECTED_MARKETS',
  GET_MARKETS: 'GET_MARKETS',
  SET_TOTAL_PRICE: 'SET_TOTAL_PRICE',
  ON_SELECT_MARKETS: 'ON_SELECT_MARKETS',
  CHANGE_STEP_ADD_NEW_MARKET: 'CHANGE_STEP_ADD_NEW_MARKET',
  LOADING_ADD_NEW_MARKET: 'LOADING_ADD_NEW_MARKET',
  GET_SCRAPING_SCHEDULE: 'GET_SCRAPING_SCHEDULE',
  GET_FREQUENCIES: 'GET_FREQUENCIES',
  SELECT_FREQUENCY: 'SELECT_FREQUENCY',
  TIME_OF_DAYS: 'TIME_OF_DAYS',
  SET_PAY_PRICE: 'SET_PAY_PRICE',
  PAY_LOADING: 'PAY_LOADING',
  SET_NEW_PRICE: 'SET_NEW_PRICE',
  SET_CURRENT_MARKETPLACES: 'SET_CURRENT_MARKETPLACES',
  LOADING_BUTTON: 'LOADING_BUTTON',

  //dashboard action types
  LOADING_INITIAL_DATA_DASHBOARD: 'LOADING_INITIAL_DATA_DASHBOARD',
  GET_SCRAP_SETTINGS_DATA_FOR_DASHBOARD: 'GET_SCRAP_SETTINGS_DATA_FOR_DASHBOARD',
  GET_BRAND_STRENGTH_DATA_FOR_DASHBOARD: 'GET_BRAND_STRENGTH_DATA_FOR_DASHBOARD',
  LOADING_SETTINGS_DATA_FOR_DASHBOARD: 'LOADING_SETTINGS_DATA_FOR_DASHBOARD',
  LOADING_MAP_VIOLATION_DATA_FOR_DASHBOARD: 'LOADING_MAP_VIOLATION_DATA_FOR_DASHBOARD',
  LOADING_BRAND_STRENGTH_DATA_FOR_DASHBOARD: 'LOADING_BRAND_STRENGTH_DATA_FOR_DASHBOARD',
  GET_MAP_VIOLATION_DATA_FOR_DASHBOARD: 'GET_MAP_VIOLATION_DATA_FOR_DASHBOARD',
  GET_DAILY_REPORTS_MAP_VIOLATION_DATA_FOR_DASHBOARD: 'GET_DAILY_REPORTS_MAP_VIOLATION_DATA_FOR_DASHBOARD',
  LOADING_DAILY_REPORTS_MAP_VIOLATION_DATA_FOR_DASHBOARD: 'LOADING_DAILY_REPORTS_MAP_VIOLATION_DATA_FOR_DASHBOARD',
  GET_STATS_DASHBOARD: 'GET_STATS_DASHBOARD',
  LOADING_STATS_DASHBOARD: 'LOADING_STATS_DASHBOARD',

  //map-violation action types
  GET_INITIAL_FILTER_OPTIONS: 'GET_INITIAL_FILTER_OPTIONS',
  GET_INITIAL_DATA_MAP_VIOLATION: 'GET_INITIAL_DATA_MAP_VIOLATION',
  SET_FILTER_DATE: 'SET_FILTER_DATE',
  SET_FILTER_TIME: 'SET_FILTER_TIME',
  GET_SCRAPED_DATA_CHECKED: 'GET_SCRAPED_DATA_CHECKED',
  GET_REPORT_MAP: 'GET_REPORT_MAP',
  MAP_CURRENT_PAGE: 'MAP_CURRENT_PAGE',
  ALL_MAP_COUNT: 'ALL_MAP_COUNT',
  REPORTED_VIOLATION: 'REPORTED_VIOLATION',
  NEW_ENTRY_VIOLATION: 'NEW_ENTRY_VIOLATION',
  SET_ENTRY_CHANGED_MAP_PRODUCT: 'SET_ENTRY_CHANGED_MAP_PRODUCT',

  //seller action types
  LOADING_SELLERS: 'LOADING_SELLERS',
  GET_SELLERS: 'GET_SELLERS',
  SET_ENTRY_NOTE: 'SET_ENTRY_NOTE',
  UPDATE_ENTRY_NOTE: 'UPDATE_ENTRY_NOTE',
  EMPTY_ENTRY_NOTE: 'EMPTY_ENTRY_NOTE',
  SET_ENTRY_SELLER_INFO: 'SET_ENTRY_SELLER_INFO',
  GET_REPORT_SELLER: 'GET_REPORT_SELLER',
  ALL_SELLERS_COUNT: 'ALL_SELLERS_COUNT',
  SELLERS_CURRENT_PAGE: 'SELLERS_CURRENT_PAGE',
  REPORTED_SELLER: 'REPORTED_SELLER',
  NEW_ENTRY_SELLER: 'NEW_ENTRY_SELLER',

  // client support types
  LOADING_SUPPORTS: 'LOADING_SUPPORTS',
  SET_SUPPORTS: 'SET_SUPPORTS',
  SET_FILTER_REQUEST_KEY: 'SET_FILTER_REQUEST_KEY',

  // Admin Coupon types
  GET_COUPONS: 'GET_COUPONS',
  LOADING_COUPONS: 'LOADING_COUPONS',
  EDIT_ADMIN_COUPONS_DATA: 'EDIT_ADMIN_COUPONS_DATA',

  // Change frequency types
  LOADING_FREQ_DATA: 'LOADING_FREQ_DATA',
  CHANGE_STEP_FREQUENCY: 'CHANGE_STEP_FREQUENCY',
  PAY_FREQ_LOADING: 'PAY_FREQ_LOADING',
  SET_PREMIUM_PRICE_FOR_TIME: 'SET_PREMIUM_PRICE_FOR_TIME',
  COUNTING_PAY_LOADING: 'COUNTING_PAY_LOADING',

  // account settings
  SET_EMAIL_TEMPLATES: 'SET_EMAIL_TEMPLATES',
  LOADING_TEMPLATES: 'LOADING_TEMPLATES',
  SET_LIST_FOR_REPORT: 'SET_LIST_FOR_REPORT',
  SET_USER_NOTIFICATIONS: 'SET_USER_NOTIFICATIONS',
  UPDATE_USER_NOTIFICATIONS: 'UPDATE_USER_NOTIFICATIONS',
  REMOVE_ADDITIONAL_EMAIL: 'REMOVE_ADDITIONAL_EMAIL',
  UPDATE_ADDITIONAL_EMAIL: 'UPDATE_ADDITIONAL_EMAIL',

  // user support
  SET_LOCATION_PATHS: 'SET_LOCATION_PATHS',
  GET_UNSEEN_SUPPORT_COUNT: 'GET_UNSEEN_SUPPORT_COUNT',
  GET_USER_SUPPORTS: 'GET_USER_SUPPORTS',

  // contact form
  SET_CONTACT_FORM: 'SET_CONTACT_FORM',
};
